## 线性代数
### 标量

In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

### 向量

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

### 长度、维度和形状

In [3]:
len(x),x.shape

(4, torch.Size([4]))

### 矩阵

In [4]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [16]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [17]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [18]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 张量

In [19]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 张量算法的基本性质

In [27]:
# 给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [30]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25., 594.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [31]:
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 降维

In [32]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [33]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(283.))

In [34]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([ 40.,  45., 143.,  55.]), torch.Size([4]))

In [36]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([  6., 115.,  38.,  54.,  70.]), torch.Size([5]))

In [37]:
A.sum(axis=[0, 1])  # Same as `A.sum()`

tensor(283.)

In [38]:
A.mean(), A.sum() / A.numel()

(tensor(14.1500), tensor(14.1500))

In [41]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.0000,  9.0000, 28.6000, 11.0000]),
 tensor([ 8.0000,  9.0000, 28.6000, 11.0000]))

### 非降维求和

In [42]:
# 调用函数来计算总和或均值时保持轴数不变会很有用
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[  6.],
        [115.],
        [ 38.],
        [ 54.],
        [ 70.]])

In [43]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.0348, 0.0435, 0.8609, 0.0609],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [44]:
# 沿某个轴计算A元素的累积总和
A.cumsum(axis=0)

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   6., 101.,  10.],
        [ 12.,  15., 111.,  21.],
        [ 24.,  28., 125.,  36.],
        [ 40.,  45., 143.,  55.]])

### 点积

In [45]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [46]:
torch.sum(x * y)

tensor(6.)

### 矩阵-向量积

In [47]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14., 224.,  62.,  86., 110.]))

### 矩阵-矩阵乘法

In [51]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[  6.,   6.,   6.],
        [115., 115., 115.],
        [ 38.,  38.,  38.],
        [ 54.,  54.,  54.],
        [ 70.,  70.,  70.]])

### 范数

In [52]:
# L2范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [53]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [54]:
# 弗罗贝尼乌斯范数满足向量范数的所有性质，它就像是矩阵形向量的 𝐿2 范数。 调用以下函数将计算矩阵的弗罗贝尼乌斯范数。
torch.norm(torch.ones((4, 9)))

tensor(6.)

### 作业

In [58]:
A.T.T==A

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [65]:
B = torch.randn(5,4)
A.T+B.T == (A+B).T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])