In [1]:
from numpy import *

## 产生数组

In [2]:
lst = [0, 1, 2, 3]
a = array(lst)
a

array([0, 1, 2, 3])

In [3]:
a = array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

## 数组属性

In [4]:
# 查看类型
type(a)

numpy.ndarray

In [5]:
# 查看数组中的数据类型
a.dtype

dtype('int64')

In [6]:
# 查看每个元素所占的字节
a.itemsize

8

In [7]:
# 查看形状，会返回一个元组，每个元素代表这一维的元素数目
a.shape

(4,)

In [9]:
shape(a)

(4,)

In [10]:
# 查看元素数目
a.size

4

In [11]:
size(a)

4

In [12]:
# 查看所有元素所占的空间
a.nbytes

32

In [13]:
# 查看数组维数
a.ndim

1

In [16]:
a.fill(-2.2)
a

array([-2, -2, -2, -2])

In [23]:
a = a.astype(double)
a.fill(-2.2)
a

array([-2.2, -2.2, -2.2, -2.2])

## 索引与切片

In [24]:
a = array([0, 1, 2, 3])
a[0]

0

In [25]:
a[0] = 10
a

array([10,  1,  2,  3])

In [26]:
b = a 
b[0] = 2
a,b

In [32]:
b = a.copy()
b[0] = 45
a,b

(array([11, 12, 13, 14, 15]), array([45, 12, 13, 14, 15]))

In [33]:
# 切片，支持负索引
a = array([11,12,13,14,15])
a[1:3]

array([12, 13])

In [34]:
a[1:-2]

array([12, 13])

In [35]:
a[-4:3]

array([12, 13])

In [38]:
# 省略参数
a[::3]

array([11, 14])

In [39]:
a[-2:]

array([14, 15])

In [40]:
od = array([21000, 21180, 21240, 22100, 22400])
dist = od[1:] - od[:-1]
dist

array([180,  60, 860, 300])

## 多维数组及其属性

In [43]:
a = array([[ 0, 1, 2, 3],
           [10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [44]:
a.shape

(2, 4)

In [45]:
# 2 * 4 = 8
a.size

8

In [46]:
a.ndim

2

## 多维数组索引

In [47]:
a[1, 3]

13

In [48]:
a[1, 3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [ ]:
# 返回第二行元组组成的array
a[1]

## 多维数组切片

In [49]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [50]:
a[0, 3:5]

array([3, 4])

In [51]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [52]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [53]:
# 每一维都支持切片的规则，包括负索引，省略
# [lower:upper:step]
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

## 切片是引用
切片在内存中使用的是引用机制。  
引用机制意味着，Python并没有为 b 分配新的空间来存储它的值，而是让 b 指向了 a 所分配的内存空间，因此，改变 b 会改变 a 的值

In [54]:
a = array([0,1,2,3,4])
b = a[2:4]
b

array([2, 3])

In [55]:
b[0] = 10
a

array([ 0,  1, 10,  3,  4])

In [56]:
# 这种现象在列表中并不会出现
a = [1,2,3,4,5]
b = a[2:3]
b[0] = 13234
a

[1, 2, 3, 4, 5]

In [57]:
# 一个解决方法是使用copy()方法产生一个复制，这个复制会申请新的内存
a = array([0,1,2,3,4])
b = a[2:4].copy()
b[0] = 10
a

array([0, 1, 2, 3, 4])

## 花式索引
切片只能支持连续或者等间隔的切片操作，要想实现任意位置的操作，需要使用花式索引 

## 一维花式索引

In [58]:
a = arange(0, 80, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [59]:
indices = [1, 2, -3]
y = a[indices]
y

array([10, 20, 50])

In [60]:
mask = array([0,1,1,0,0,1,0,0],
            dtype=bool)
a[mask]

array([10, 20, 50])

In [61]:
# 或者用布尔表达式生成 mask，选出了所有大于0.5的值
from numpy.random import rand
a = rand(10)
a

array([0.62769945, 0.99344327, 0.38027935, 0.06888206, 0.63484571,
       0.32757475, 0.80767383, 0.19699099, 0.05580221, 0.25917175])

In [62]:
mask = a > 0.5
a[mask]

array([0.62769945, 0.99344327, 0.63484571, 0.80767383])

## 二维花式索引

In [63]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [64]:
a[(0,1,2,3,4), (1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [65]:
a[3:, [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [66]:
mask = array([1,0,1,0,0,1],
            dtype=bool)
a[mask, 2]

array([ 2, 22, 52])

## “不完全”索引

In [67]:
y = a[:3]
y

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [70]:
condition = array([0,1,1,0,1,0],
                 dtype=bool)
a[condition]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

## 三维花式索引

In [71]:
a = arange(64)
a.shape = 4,4,4
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [72]:
y = a[:,:,[2, -1]]
y

array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [54, 55],
        [58, 59],
        [62, 63]]])

## where语句
where 函数会返回所有非零元素的索引  
where(array)

## 一维数组

In [78]:
a = array([0, 12, 5, 20])
a > 10

array([False,  True, False,  True])

In [79]:
where(a > 10)

(array([1, 3]),)

注意到 where 的返回值是一个元组。

使用元组是由于 where 可以对多维数组使用，此时返回值就是多维的

In [75]:
indices = where(a > 10)
indices = indices[0]
indices

array([1, 3])

In [80]:
indices = where(a>10)[0]
indices

array([1, 3])

In [81]:
# 可以直接用 where 的返回值进行索引
loc = where(a > 10)
a[loc]

array([12, 20])

## 多维数组

In [83]:
a = array([[0, 12, 5, 20],
           [1, 2, 11, 15]])
loc = where(a > 10)
loc

(array([0, 0, 1, 1]), array([1, 3, 2, 3]))

In [84]:
a[loc]

array([12, 20, 11, 15])

In [87]:
rows, cols = where(a > 10)
rows, cols

(array([0, 0, 1, 1]), array([1, 3, 2, 3]))

In [88]:
a[rows, cols]

array([12, 20, 11, 15])

In [89]:
a = arange(25)
a.shape = 5,5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
a > 12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [91]:
where(a > 12)

(array([2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4]),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))