In [1]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## 修改数组的形状

In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

## 使用 newaxis 增加数组维数

In [5]:
a = arange(3)
shape(a)

(3,)

In [6]:
y = a[newaxis, :]
shape(y)

(1, 3)

In [8]:
y = a[:, newaxis]
shape(y)

(3, 1)

In [10]:
y = a[newaxis, newaxis, :]
shape(y)

(1, 1, 3)

## squeeze 方法去除多余的轴
squeeze 返回一个将所有长度为1的维度去除的新数组

In [11]:
a = arange(6)
a.shape = (2,1,3)

In [12]:
b = a.squeeze()
b.shape

(2, 3)

## 数组转置

In [13]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [14]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [15]:
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

## 数组连接

In [16]:
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
x.shape, y.shape

((2, 3), (2, 3))

In [17]:
z = concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [18]:
z = concatenate((x,y), axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [19]:
z.shape

(2, 6)

In [21]:
z = array((x,y))
z.shape

(2, 2, 3)

In [22]:
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

In [23]:
vstack((x, y)).shape

(4, 3)

In [24]:
hstack((x, y)).shape

(2, 6)

In [25]:
dstack((x, y)).shape

(2, 3, 2)

## Flatten 数组
flatten 方法的作用是将多维数组转化为1维数组

In [27]:
a = array([[0,1],
           [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

In [29]:
# 返回的是数组的复制，因此，改变 b 并不会影响 a 的值
b[0] = 10
a, b

(array([[0, 1],
        [2, 3]]),
 array([10,  1,  2,  3]))

## flat 属性
a.flat 相当于返回了所有元组组成的一个迭代器

In [38]:
# 修改 b 的值会影响 a
b = a.flat
b[0]

0

In [39]:
b[0] = 10

In [40]:
a.flat[:]

array([10,  1,  2,  3])

## ravel 方法

In [51]:
# 修改 b 会改变 a
a = array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

In [48]:
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

In [49]:
# 修改 b 并不会改变 aa 的值，原因是我们用来 ravel 的对象 aa 本身是 a 的一个view
a = array([[0,1],
           [2,3]])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [50]:
b[0] = 10
aa

array([[0, 2],
       [1, 3]])