In [1]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## 求和

In [5]:
a = array([[1, 2, 3],
            [4, 5, 6]])
a.sum(), sum(a)

(21, 21)

In [6]:
a.sum(axis=1), sum(a, axis=1)

(array([ 6, 15]), array([ 6, 15]))

## 求积

In [7]:
a.prod(), prod(a)

(720, 720)

In [8]:
a.prod(axis=1), prod(a, axis=1)

(array([  6, 120]), array([  6, 120]))

## 求最大最小值

In [11]:
from numpy.random import rand
a = rand(3, 4)
%precision 3
a

array([[0.587, 0.401, 0.646, 0.26 ],
       [0.543, 0.493, 0.408, 0.915],
       [0.788, 0.408, 0.376, 0.338]])

In [19]:
a.min(), a.min(axis=1)

(0.26038540399443877, array([0.26 , 0.408, 0.338]))

In [20]:
a.max(), a.max(axis=1)

(0.9154714516318021, array([0.646, 0.915, 0.788]))

## 最大最小值的位置

In [22]:
a.argmin(),a.argmin(axis=1)

(3, array([3, 2, 3]))

## 均值

In [30]:
a = array([[1,2,3],[4,5,6]])

In [32]:
a.mean(), mean(a), a.mean(axis=1), mean(a,axis=1)

(3.5, 3.5, array([2., 5.]), array([2., 5.]))

In [35]:
average(a, axis=1)

array([2., 5.])

In [41]:
# average 函数还支持加权平均：
average(a, axis=1, weights=[1,2,3])

array([2.333, 5.333])

## 标准差

In [44]:
a.std(axis=1), std(a,axis=1)

(array([0.816, 0.816]), array([0.816, 0.816]))

In [48]:
# 方差
a.var(axis=1),var(a, axis=1)

(array([0.667, 0.667]), array([0.667, 0.667]))

## clip 方法
将数值限制在某个范围

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
# 小于3的变成3，大于5的变成5
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

## ptp方法
计算最大值和最小值之差

In [51]:
a.ptp(axis=1), a.ptp(axis=1)

(array([2, 2]), array([2, 2]))

## round 方法
近似，默认到整数

In [52]:
a = array([1.35, 2.5, 1.5])

In [53]:
a.round(), a.round(decimals=1)


(array([1., 2., 2.]), array([1.4, 2.5, 1.5]))