# 数组与字符串的转换

In [1]:
import numpy as np

## tostring方法

In [4]:
a = np.array([[1,2],[3,4]], dtype=np.uint8)
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [5]:
a.tostring()

/Users/huangjiyong/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  """Entry point for launching an IPython kernel.


b'\x01\x02\x03\x04'

In [9]:
a.tostring(order='F')

/Users/huangjiyong/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  """Entry point for launching an IPython kernel.


b'\x01\x03\x02\x04'

## fromstring 函数
可以使用 fromstring 函数从字符串中读出数据，不过要指定类型

In [11]:
s = a.tostring()
a = np.fromstring(s, dtype=np.uint8)
a

/Users/huangjiyong/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  """Entry point for launching an IPython kernel.
/Users/huangjiyong/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


array([1, 2, 3, 4], dtype=uint8)

In [13]:
a.shape = 2,2
a

array([[1, 2],
       [3, 4]], dtype=uint8)