In [1]:
from numpy import *

## 复数数组

In [11]:
a = array([1+ 1j, 2, 3, 4])
a.dtype

dtype('complex128')

In [10]:
# 对于复数我们可以查看它的实部和虚部
a.real,a.imag

(array([1., 2., 3., 4.]), array([1., 2., 3., 4.]))

In [12]:
# 设置它们的值
a.imag = [1, 2, 3, 4]
a

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [13]:
# 查看复共轭
a.conj()

array([1.-1.j, 2.-2.j, 3.-3.j, 4.-4.j])

In [14]:
# 这些属性方法可以用在浮点数或者整数数组上
a = array([0., 1, 2, 3])
a.dtype

dtype('float64')

In [15]:
a.real, a.imag

(array([0., 1., 2., 3.]), array([0., 0., 0., 0.]))

In [17]:
a.conj()

array([0., 1., 2., 3.])

In [19]:
# 会报错 这里虚部是只读的，并不能修改它的值
a.imag = [1,2,3,4]

TypeError: array does not have imaginary part to set

## 指定数组类型

In [20]:
a = array([0, 1.0, 2, 3])
a.dtype

dtype('float64')

In [21]:
a.nbytes

32

In [23]:
a = array([0,1.0,2,3],dtype=float32)
a.dtype

dtype('float32')

In [26]:
a = a.astype('float64')

In [30]:
a.dtype

dtype('float64')

## asarray 函数
当类型相同的时候，asarray 并不会产生新的对象，而是使用同一个引用  
有些时候为了保证我们的输入值是数组，我们需要将其使用 asarray 转化，当它已经是数组的时候，并不会产生新的对象，这样保证了效率。

In [32]:
b = asarray(a, dtype=float32)
b.dtype

dtype('float32')

In [34]:
a == b, a is b

(array([ True,  True,  True,  True]), False)

In [35]:
b = asarray(a, dtype=float64)
b.dtype

dtype('float64')

In [36]:
a == b, a is b

(array([ True,  True,  True,  True]), True)

## view 方法
view 会将 a 在内存中的表示看成是 uint8 进行解析,共用一块内存

In [37]:
a = array((1,2,3,4), dtype=int32)
a

array([1, 2, 3, 4], dtype=int32)

In [38]:
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

In [39]:
a[0] = 2**30
a

array([1073741824,          2,          3,          4], dtype=int32)

In [40]:
b

array([ 0,  0,  0, 64,  2,  0,  0,  0,  3,  0,  0,  0,  4,  0,  0,  0],
      dtype=uint8)