In [1]:
%pylab


Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## sort 函数

In [15]:
names = array(['bob', 'sue', 'jan', 'ad'])
weights = array([20.8, 93.2, 53.4, 61.8])

sort(weights)

array([20.8, 53.4, 61.8, 93.2])

## argsort 函数
argsort 返回从小到大的排列在数组中的索引位置

In [16]:
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1])

In [17]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

In [18]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'], dtype='<U3')

sort 和 argsort 方法
数组也支持方法操作：

In [19]:
data = array([20.8,  93.2,  53.4,  61.8])
data.argsort()

array([0, 2, 3, 1])

In [20]:
data

array([20.8, 93.2, 53.4, 61.8])

In [23]:
# sort方法会改变数组的值
data.sort()

In [22]:
data

array([20.8, 53.4, 61.8, 93.2])

## 二维数组排序
对于多维数组，sort方法默认沿着最后一维开始排序

In [24]:
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [27]:
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [28]:
sort(a, axis = 0)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

## searchsorted 函数
searchsorted 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

例如 0.1 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 1 处，故第一个返回值为 1

In [29]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])

In [30]:
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1])

In [31]:
sorted_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])